import { Team } from './types';

export const TEAMS: Team[] = [
  { id: 'ancona', name: 'Ancona', colors: ['#CC0000', '#FFFFFF'] },
  { id: 'ascoli', name: 'Ascoli', colors: ['#FFFFFF', '#000000'] }, // Black and White, used white primarily for text visibility on dark if needed, but usually strip is bg
  { id: 'atalanta', name: 'Atalanta', colors: ['#1E71B8', '#000000'] },
  { id: 'bari', name: 'Bari', colors: ['#FFFFFF', '#CC0000'] },
  { id: 'benevento', name: 'Benevento', colors: ['#FFFF00', '#CC0000'] },
  { id: 'bologna', name: 'Bologna', colors: ['#1A2F48', '#A21C26'] },
  { id: 'brescia', name: 'Brescia', colors: ['#0066CC', '#FFFFFF'] },
  { id: 'cagliari', name: 'Cagliari', colors: ['#000099', '#990000'] },
  { id: 'carpi', name: 'Carpi', colors: ['#CC0000', '#FFFFFF'] },
  { id: 'catania', name: 'Catania', colors: ['#CC0000', '#99CCFF'] },
  { id: 'cesena', name: 'Cesena', colors: ['#000000', '#FFFFFF'] },
  { id: 'chievo', name: 'Chievo Verona', colors: ['#FFFF00', '#0000FF'] },
  { id: 'como', name: 'Como', colors: ['#0000FF', '#FFFFFF'] },
  { id: 'cremonese', name: 'Cremonese', colors: ['#989898', '#A91018'] },
  { id: 'crotone', name: 'Crotone', colors: ['#000066', '#CC0000'] },
  { id: 'empoli', name: 'Empoli', colors: ['#00579C', '#FFFFFF'] },
  { id: 'fiorentina', name: 'Fiorentina', colors: ['#482E92', '#FFFFFF'] },
  { id: 'foggia', name: 'Foggia', colors: ['#CC0000', '#000000'] },
  { id: 'frosinone', name: 'Frosinone', colors: ['#FFFF00', '#0000FF'] },
  { id: 'genoa', name: 'Genoa', colors: ['#CC0000', '#000066'] },
  { id: 'inter', name: 'Inter', colors: ['#0068A8', '#000000'] },
  { id: 'juventus', name: 'Juventus', colors: ['#FFFFFF', '#000000'] },
  { id: 'lazio', name: 'Lazio', colors: ['#87D8F7', '#FFFFFF'] },
  { id: 'lecce', name: 'Lecce', colors: ['#FFFF00', '#CC0000'] },
  { id: 'livorno', name: 'Livorno', colors: ['#660000', '#FFFFFF'] }, // Dark red/brown
  { id: 'messina', name: 'Messina', colors: ['#FFFF00', '#CC0000'] },
  { id: 'milan', name: 'Milan', colors: ['#FB090B', '#000000'] },
  { id: 'modena', name: 'Modena', colors: ['#FFFF00', '#0000FF'] },
  { id: 'monza', name: 'Monza', colors: ['#E30613', '#FFFFFF'] },
  { id: 'napoli', name: 'Napoli', colors: ['#0067B3', '#FFFFFF'] },
  { id: 'novara', name: 'Novara', colors: ['#0000FF', '#FFFFFF'] },
  { id: 'padova', name: 'Padova', colors: ['#CC0000', '#FFFFFF'] },
  { id: 'palermo', name: 'Palermo', colors: ['#FFC0CB', '#000000'] },
  { id: 'parma', name: 'Parma', colors: ['#0000FF', '#FFFF00'] },
  { id: 'perugia', name: 'Perugia', colors: ['#CC0000', '#FFFFFF'] },
  { id: 'pescara', name: 'Pescara', colors: ['#99CCFF', '#FFFFFF'] },
  { id: 'piacenza', name: 'Piacenza', colors: ['#CC0000', '#FFFFFF'] },
  { id: 'pisa', name: 'Pisa', colors: ['#0000FF', '#000000'] },
  { id: 'reggiana', name: 'Reggiana', colors: ['#800000', '#FFFFFF'] },
  { id: 'reggina', name: 'Reggina', colors: ['#800000', '#000000'] },
  { id: 'roma', name: 'Roma', colors: ['#8B0304', '#F6A323'] },
  { id: 'salernitana', name: 'Salernitana', colors: ['#8A1E41', '#FFFFFF'] },
  { id: 'sampdoria', name: 'Sampdoria', colors: ['#1B5497', '#FFFFFF'] },
  { id: 'sassuolo', name: 'Sassuolo', colors: ['#00A752', '#000000'] },
  { id: 'siena', name: 'Siena', colors: ['#FFFFFF', '#000000'] },
  { id: 'spal', name: 'Spal', colors: ['#99CCFF', '#FFFFFF'] },
  { id: 'spezia', name: 'Spezia', colors: ['#FFFFFF', '#000000'] },
  { id: 'torino', name: 'Torino', colors: ['#8A1E03', '#FFFFFF'] },
  { id: 'treviso', name: 'Treviso', colors: ['#99CCFF', '#FFFFFF'] },
  { id: 'udinese', name: 'Udinese', colors: ['#FFFFFF', '#000000'] },
  { id: 'venezia', name: 'Venezia', colors: ['#FF6600', '#009900'] },
  { id: 'verona', name: 'Verona', colors: ['#000099', '#FFFF00'] },
  { id: 'vicenza', name: 'Vicenza', colors: ['#CC0000', '#FFFFFF'] },
];

export const MOCK_HISTORY = [
  { id: 1, result: 'WIN', score: '2-1', opponent: 'AI (Gemini)', date: 'Today' },
  { id: 2, result: 'LOSS', score: '1-3', opponent: 'AI (Gemini)', date: 'Yesterday' },
];